/** @type {import('tailwindcss').Config} */
// Colours by meaning (values in src/theme/tokens.css, light and dark). `bg-primary/10` works because each is an rgb triplet.
const token = (name) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  darkMode: 'class',
  // Hover styles only where a pointer can hover: on touch screens :hover sticks after a tap and makes things look selected.
  future: { hoverOnlyWhenSupported: true },
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: token('canvas'),
        surface: token('surface'),
        soft: token('soft'),
        fill: token('fill'),
        bubble: token('bubble'),
        line: token('line'),
        'line-strong': token('line-strong'),
        ink: token('ink'),
        body: token('body'),
        muted: token('muted'),
        faint: token('faint'),
        inverse: token('inverse'),
        'on-inverse': token('on-inverse'),
        scrim: token('scrim'),
        primary: token('primary'),
        'primary-hover': token('primary-hover'),
        'primary-tint': token('primary-tint'),
        'primary-soft': token('primary-soft'),
        danger: token('danger'),
        'danger-ink': token('danger-ink'),
        success: token('success'),
        'success-ink': token('success-ink'),
        'success-tint': token('success-tint'),
        blue: token('blue'),
        'blue-tint': token('blue-tint'),
        violet: token('violet'),
        'violet-tint': token('violet-tint'),
        amber: token('amber'),
        'amber-tint': token('amber-tint'),
        warn: token('warn'),
        'warn-ink': token('warn-ink'),
        question: token('question'),
        'question-line': token('question-line'),
        info: token('info'),
        'info-line': token('info-line'),
        note: token('note'),
        'note-line': token('note-line'),
        // Cursor Design System Palette
        cursor: {
          primary: '#f54e00',
          'primary-active': '#d04200',
          ink: '#26251e',
          body: '#5a5852',
          'body-strong': '#26251e',
          muted: '#807d72',
          'muted-soft': '#a09c92',
          hairline: '#e6e5e0',
          'hairline-soft': '#efeee8',
          'hairline-strong': '#cfcdc4',
          canvas: '#f7f7f4',
          'canvas-soft': '#fafaf7',
          'surface-card': '#ffffff',
          'surface-strong': '#e6e5e0',
          'on-primary': '#ffffff',
          // In-product AI action pastels
          'timeline-thinking': '#dfa88f',
          'timeline-grep': '#9fc9a2',
          'timeline-read': '#9fbbe0',
          'timeline-edit': '#c0a8dd',
          'timeline-done': '#c08532',
          'semantic-success': '#1f8a65',
          'semantic-error': '#cf2d56',
        },
        aws: {
          orange: '#f54e00',
          blue: '#9fbbe0',
          db: '#9fc9a2',
          cache: '#dfa88f',
          gateway: '#c0a8dd',
          queue: '#c08532',
          storage: '#9fbbe0',
          compute: '#f54e00',
        }
      },
      fontFamily: {
        sans: ['"Inter Variable"', 'Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        // The design's small mono labels ("ECS FARGATE", "REQUIREMENTS"): tiny, uppercase, loosely tracked.
        '2xs': ['10px', { lineHeight: '14px', letterSpacing: '0.06em' }],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'pill': '9999px',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
