// Icons for diagrams: a curated set from Phosphor Icons (https://phosphoricons.com, MIT), drawn in the duotone weight.
import {
  Airplane,
  Anchor,
  Archive,
  At,
  Atom,
  Bank,
  Bell,
  Binoculars,
  Boat,
  Book,
  BookOpen,
  Bookmark,
  Brain,
  Broadcast,
  Browser,
  Bug,
  Buildings,
  Calendar,
  Camera,
  Car,
  ChartBar,
  ChartLine,
  ChartPie,
  ChatCircle,
  ChatsCircle,
  CheckCircle,
  ClipboardText,
  Clock,
  Cloud,
  CloudArrowUp,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Cube,
  Database,
  Desktop,
  DeviceMobile,
  Diamond,
  Drop,
  Envelope,
  Eye,
  FileText,
  Files,
  FilmStrip,
  Fingerprint,
  Fire,
  FirstAid,
  Flag,
  Flask,
  FlowArrow,
  FolderSimple,
  Funnel,
  GameController,
  Gauge,
  Gavel,
  Gear,
  GearSix,
  Gift,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  GlobeHemisphereWest,
  GraduationCap,
  Graph,
  Hammer,
  Handshake,
  HardDrives,
  Hash,
  Headphones,
  Heart,
  Heartbeat,
  House,
  Image,
  Infinity,
  Info,
  Kanban,
  Key,
  Laptop,
  Layout,
  Leaf,
  Lifebuoy,
  Lightbulb,
  Lightning,
  Link,
  Lock,
  LockKey,
  MagicWand,
  MagnifyingGlass,
  MapPin,
  Medal,
  Microphone,
  Moon,
  Mountains,
  MusicNotes,
  Network,
  Notebook,
  Package,
  Paperclip,
  Planet,
  Plug,
  PlugsConnected,
  Prohibit,
  Pulse,
  PuzzlePiece,
  Question,
  Queue,
  Radio,
  Receipt,
  Robot,
  Rocket,
  Scales,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sparkle,
  Stack,
  Star,
  Storefront,
  Sun,
  Table,
  Tag,
  Target,
  Terminal,
  TerminalWindow,
  Timer,
  Train,
  Tree,
  TreeStructure,
  Trophy,
  Truck,
  User,
  UserCircle,
  Users,
  Wallet,
  Warning,
  WifiHigh,
  Wind,
  Wrench,
  type Icon,
} from '@phosphor-icons/react';

export interface DiagramIconEntry {
  name: string;
  label: string;
  group: string;
  Icon: Icon;
}

export const ICON_GROUPS = ["Build", "Systems", "Security", "Data", "People", "Commerce", "World"] as const;

export const ICONS: readonly DiagramIconEntry[] = [
  { name: 'Rocket', label: 'Rocket', group: 'Build', Icon: Rocket },
  { name: 'Cube', label: 'Cube', group: 'Build', Icon: Cube },
  { name: 'Package', label: 'Package', group: 'Build', Icon: Package },
  { name: 'Stack', label: 'Stack', group: 'Build', Icon: Stack },
  { name: 'Hammer', label: 'Hammer', group: 'Build', Icon: Hammer },
  { name: 'Wrench', label: 'Wrench', group: 'Build', Icon: Wrench },
  { name: 'Gear', label: 'Gear', group: 'Build', Icon: Gear },
  { name: 'GearSix', label: 'Gear Six', group: 'Build', Icon: GearSix },
  { name: 'Code', label: 'Code', group: 'Build', Icon: Code },
  { name: 'Terminal', label: 'Terminal', group: 'Build', Icon: Terminal },
  { name: 'TerminalWindow', label: 'Terminal Window', group: 'Build', Icon: TerminalWindow },
  { name: 'Bug', label: 'Bug', group: 'Build', Icon: Bug },
  { name: 'Cpu', label: 'Cpu', group: 'Build', Icon: Cpu },
  { name: 'HardDrives', label: 'Hard Drives', group: 'Build', Icon: HardDrives },
  { name: 'Desktop', label: 'Desktop', group: 'Build', Icon: Desktop },
  { name: 'Laptop', label: 'Laptop', group: 'Build', Icon: Laptop },
  { name: 'DeviceMobile', label: 'Device Mobile', group: 'Build', Icon: DeviceMobile },
  { name: 'Browser', label: 'Browser', group: 'Build', Icon: Browser },
  { name: 'Plug', label: 'Plug', group: 'Build', Icon: Plug },
  { name: 'PlugsConnected', label: 'Plugs Connected', group: 'Build', Icon: PlugsConnected },
  { name: 'PuzzlePiece', label: 'Puzzle Piece', group: 'Build', Icon: PuzzlePiece },
  { name: 'Flask', label: 'Flask', group: 'Build', Icon: Flask },
  { name: 'Atom', label: 'Atom', group: 'Build', Icon: Atom },
  { name: 'Database', label: 'Database', group: 'Systems', Icon: Database },
  { name: 'Cloud', label: 'Cloud', group: 'Systems', Icon: Cloud },
  { name: 'CloudArrowUp', label: 'Cloud Arrow Up', group: 'Systems', Icon: CloudArrowUp },
  { name: 'Lightning', label: 'Lightning', group: 'Systems', Icon: Lightning },
  { name: 'Network', label: 'Network', group: 'Systems', Icon: Network },
  { name: 'Graph', label: 'Graph', group: 'Systems', Icon: Graph },
  { name: 'TreeStructure', label: 'Tree Structure', group: 'Systems', Icon: TreeStructure },
  { name: 'FlowArrow', label: 'Flow Arrow', group: 'Systems', Icon: FlowArrow },
  { name: 'GitBranch', label: 'Git Branch', group: 'Systems', Icon: GitBranch },
  { name: 'GitMerge', label: 'Git Merge', group: 'Systems', Icon: GitMerge },
  { name: 'GitPullRequest', label: 'Git Pull Request', group: 'Systems', Icon: GitPullRequest },
  { name: 'Queue', label: 'Queue', group: 'Systems', Icon: Queue },
  { name: 'Funnel', label: 'Funnel', group: 'Systems', Icon: Funnel },
  { name: 'Table', label: 'Table', group: 'Systems', Icon: Table },
  { name: 'Broadcast', label: 'Broadcast', group: 'Systems', Icon: Broadcast },
  { name: 'WifiHigh', label: 'Wifi High', group: 'Systems', Icon: WifiHigh },
  { name: 'Globe', label: 'Globe', group: 'Systems', Icon: Globe },
  { name: 'GlobeHemisphereWest', label: 'Globe Hemisphere West', group: 'Systems', Icon: GlobeHemisphereWest },
  { name: 'Link', label: 'Link', group: 'Systems', Icon: Link },
  { name: 'Infinity', label: 'Infinity', group: 'Systems', Icon: Infinity },
  { name: 'Hash', label: 'Hash', group: 'Systems', Icon: Hash },
  { name: 'At', label: 'At', group: 'Systems', Icon: At },
  { name: 'Shield', label: 'Shield', group: 'Security', Icon: Shield },
  { name: 'ShieldCheck', label: 'Shield Check', group: 'Security', Icon: ShieldCheck },
  { name: 'Lock', label: 'Lock', group: 'Security', Icon: Lock },
  { name: 'LockKey', label: 'Lock Key', group: 'Security', Icon: LockKey },
  { name: 'Key', label: 'Key', group: 'Security', Icon: Key },
  { name: 'Fingerprint', label: 'Fingerprint', group: 'Security', Icon: Fingerprint },
  { name: 'Eye', label: 'Eye', group: 'Security', Icon: Eye },
  { name: 'Prohibit', label: 'Prohibit', group: 'Security', Icon: Prohibit },
  { name: 'Warning', label: 'Warning', group: 'Security', Icon: Warning },
  { name: 'Lifebuoy', label: 'Lifebuoy', group: 'Security', Icon: Lifebuoy },
  { name: 'Scales', label: 'Scales', group: 'Security', Icon: Scales },
  { name: 'Gavel', label: 'Gavel', group: 'Security', Icon: Gavel },
  { name: 'ChartBar', label: 'Chart Bar', group: 'Data', Icon: ChartBar },
  { name: 'ChartLine', label: 'Chart Line', group: 'Data', Icon: ChartLine },
  { name: 'ChartPie', label: 'Chart Pie', group: 'Data', Icon: ChartPie },
  { name: 'Pulse', label: 'Pulse', group: 'Data', Icon: Pulse },
  { name: 'Gauge', label: 'Gauge', group: 'Data', Icon: Gauge },
  { name: 'Timer', label: 'Timer', group: 'Data', Icon: Timer },
  { name: 'Clock', label: 'Clock', group: 'Data', Icon: Clock },
  { name: 'Calendar', label: 'Calendar', group: 'Data', Icon: Calendar },
  { name: 'Kanban', label: 'Kanban', group: 'Data', Icon: Kanban },
  { name: 'Layout', label: 'Layout', group: 'Data', Icon: Layout },
  { name: 'Target', label: 'Target', group: 'Data', Icon: Target },
  { name: 'Trophy', label: 'Trophy', group: 'Data', Icon: Trophy },
  { name: 'Medal', label: 'Medal', group: 'Data', Icon: Medal },
  { name: 'Files', label: 'Files', group: 'Data', Icon: Files },
  { name: 'FolderSimple', label: 'Folder Simple', group: 'Data', Icon: FolderSimple },
  { name: 'FileText', label: 'File Text', group: 'Data', Icon: FileText },
  { name: 'ClipboardText', label: 'Clipboard Text', group: 'Data', Icon: ClipboardText },
  { name: 'Notebook', label: 'Notebook', group: 'Data', Icon: Notebook },
  { name: 'Archive', label: 'Archive', group: 'Data', Icon: Archive },
  { name: 'Users', label: 'Users', group: 'People', Icon: Users },
  { name: 'User', label: 'User', group: 'People', Icon: User },
  { name: 'UserCircle', label: 'User Circle', group: 'People', Icon: UserCircle },
  { name: 'Handshake', label: 'Handshake', group: 'People', Icon: Handshake },
  { name: 'ChatCircle', label: 'Chat Circle', group: 'People', Icon: ChatCircle },
  { name: 'ChatsCircle', label: 'Chats Circle', group: 'People', Icon: ChatsCircle },
  { name: 'Envelope', label: 'Envelope', group: 'People', Icon: Envelope },
  { name: 'Bell', label: 'Bell', group: 'People', Icon: Bell },
  { name: 'Heart', label: 'Heart', group: 'People', Icon: Heart },
  { name: 'Heartbeat', label: 'Heartbeat', group: 'People', Icon: Heartbeat },
  { name: 'FirstAid', label: 'First Aid', group: 'People', Icon: FirstAid },
  { name: 'GraduationCap', label: 'Graduation Cap', group: 'People', Icon: GraduationCap },
  { name: 'Brain', label: 'Brain', group: 'People', Icon: Brain },
  { name: 'Robot', label: 'Robot', group: 'People', Icon: Robot },
  { name: 'Lightbulb', label: 'Lightbulb', group: 'People', Icon: Lightbulb },
  { name: 'Sparkle', label: 'Sparkle', group: 'People', Icon: Sparkle },
  { name: 'MagicWand', label: 'Magic Wand', group: 'People', Icon: MagicWand },
  { name: 'CreditCard', label: 'Credit Card', group: 'Commerce', Icon: CreditCard },
  { name: 'Wallet', label: 'Wallet', group: 'Commerce', Icon: Wallet },
  { name: 'Receipt', label: 'Receipt', group: 'Commerce', Icon: Receipt },
  { name: 'ShoppingCart', label: 'Shopping Cart', group: 'Commerce', Icon: ShoppingCart },
  { name: 'Storefront', label: 'Storefront', group: 'Commerce', Icon: Storefront },
  { name: 'Bank', label: 'Bank', group: 'Commerce', Icon: Bank },
  { name: 'Truck', label: 'Truck', group: 'Commerce', Icon: Truck },
  { name: 'MapPin', label: 'Map Pin', group: 'Commerce', Icon: MapPin },
  { name: 'Compass', label: 'Compass', group: 'Commerce', Icon: Compass },
  { name: 'Flag', label: 'Flag', group: 'Commerce', Icon: Flag },
  { name: 'Gift', label: 'Gift', group: 'Commerce', Icon: Gift },
  { name: 'Tag', label: 'Tag', group: 'Commerce', Icon: Tag },
  { name: 'Bookmark', label: 'Bookmark', group: 'Commerce', Icon: Bookmark },
  { name: 'Crown', label: 'Crown', group: 'Commerce', Icon: Crown },
  { name: 'Diamond', label: 'Diamond', group: 'Commerce', Icon: Diamond },
  { name: 'Star', label: 'Star', group: 'Commerce', Icon: Star },
  { name: 'Sun', label: 'Sun', group: 'World', Icon: Sun },
  { name: 'Moon', label: 'Moon', group: 'World', Icon: Moon },
  { name: 'Leaf', label: 'Leaf', group: 'World', Icon: Leaf },
  { name: 'Tree', label: 'Tree', group: 'World', Icon: Tree },
  { name: 'Fire', label: 'Fire', group: 'World', Icon: Fire },
  { name: 'Drop', label: 'Drop', group: 'World', Icon: Drop },
  { name: 'Wind', label: 'Wind', group: 'World', Icon: Wind },
  { name: 'Mountains', label: 'Mountains', group: 'World', Icon: Mountains },
  { name: 'Planet', label: 'Planet', group: 'World', Icon: Planet },
  { name: 'House', label: 'House', group: 'World', Icon: House },
  { name: 'Buildings', label: 'Buildings', group: 'World', Icon: Buildings },
  { name: 'Airplane', label: 'Airplane', group: 'World', Icon: Airplane },
  { name: 'Car', label: 'Car', group: 'World', Icon: Car },
  { name: 'Train', label: 'Train', group: 'World', Icon: Train },
  { name: 'Boat', label: 'Boat', group: 'World', Icon: Boat },
  { name: 'Anchor', label: 'Anchor', group: 'World', Icon: Anchor },
  { name: 'Coffee', label: 'Coffee', group: 'World', Icon: Coffee },
  { name: 'Camera', label: 'Camera', group: 'World', Icon: Camera },
  { name: 'Image', label: 'Image', group: 'World', Icon: Image },
  { name: 'FilmStrip', label: 'Film Strip', group: 'World', Icon: FilmStrip },
  { name: 'MusicNotes', label: 'Music Notes', group: 'World', Icon: MusicNotes },
  { name: 'Microphone', label: 'Microphone', group: 'World', Icon: Microphone },
  { name: 'Headphones', label: 'Headphones', group: 'World', Icon: Headphones },
  { name: 'GameController', label: 'Game Controller', group: 'World', Icon: GameController },
  { name: 'Book', label: 'Book', group: 'World', Icon: Book },
  { name: 'BookOpen', label: 'Book Open', group: 'World', Icon: BookOpen },
  { name: 'Question', label: 'Question', group: 'World', Icon: Question },
  { name: 'Info', label: 'Info', group: 'World', Icon: Info },
  { name: 'CheckCircle', label: 'Check Circle', group: 'World', Icon: CheckCircle },
  { name: 'Binoculars', label: 'Binoculars', group: 'World', Icon: Binoculars },
  { name: 'MagnifyingGlass', label: 'Magnifying Glass', group: 'World', Icon: MagnifyingGlass },
  { name: 'Paperclip', label: 'Paperclip', group: 'World', Icon: Paperclip },
  { name: 'Radio', label: 'Radio', group: 'World', Icon: Radio },
];

/** The colours an icon can have: each is a theme colour, so it reads well in the light and the dark theme. */
export const ICON_COLORS = [
  { id: 'slate', label: 'Slate', css: '--body' },
  { id: 'blue', label: 'Blue', css: '--blue' },
  { id: 'violet', label: 'Violet', css: '--violet' },
  { id: 'orange', label: 'Orange', css: '--primary' },
  { id: 'green', label: 'Green', css: '--success' },
  { id: 'amber', label: 'Amber', css: '--amber' },
  { id: 'rose', label: 'Rose', css: '--danger' },
] as const;
export type IconColor = (typeof ICON_COLORS)[number]['id'];

export const DEFAULT_ICON = 'TreeStructure.slate';

const BY_NAME = new Map(ICONS.map((i) => [i.name, i]));
const COLOR_BY_ID = new Map<string, (typeof ICON_COLORS)[number]>(ICON_COLORS.map((c) => [c.id, c]));

/** "Rocket.violet" -> its icon and colour; anything unknown falls back to the default, so a stale value never breaks a screen. */
export function parseIcon(value: string | null | undefined): { entry: DiagramIconEntry; color: (typeof ICON_COLORS)[number] } {
  const [name, color] = (value ?? DEFAULT_ICON).split('.');
  return { entry: BY_NAME.get(name ?? '') ?? BY_NAME.get('TreeStructure')!, color: COLOR_BY_ID.get(color ?? '') ?? ICON_COLORS[0] };
}

export const joinIcon = (name: string, color: string): string => `${name}.${color}`;

/** Icons matching what was typed (name or group), in list order. */
export function searchIcons(query: string): DiagramIconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...ICONS];
  return ICONS.filter((i) => i.label.toLowerCase().includes(q) || i.group.toLowerCase().includes(q));
}
